fix: support tilde expansion
denoland/deno_task_shell pull request #128
Opened 2024-11-27 12:50 UTC by HasanAlrimawi

This PR suggests possible solution for [#26676](https://github.com/denoland/deno/issues/26676)

**Changes**
- Expand tilde to home directory whenever applicable (being mentioned as home directory).

2024-11-27 12:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/denoland/deno_task_shell?pullRequest=128) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/denoland/deno_task_shell?pullRequest=128) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/denoland/deno_task_shell?pullRequest=128) it.</sub>

2024-11-27 20:16 UTC, dsherret requested changes
Thanks! Let's shift this to happen when executing and not when parsing.

2024-11-27 20:16 UTC, dsherret commented on src/parser.rs
> +  }
I don't think we should do this while parsing, but instead during execution. The home directory in the shell might change while running. For example, the following test case should pass:

```sh
$ export HOME=test ; echo ~/test/~/test
test/test/~/test
```

2024-12-02 14:39 UTC, HasanAlrimawi commented
@dsherret 
I was able to solve the testcase you mentioned. However, in `src/shell/execute.rs fn execute_sequential_list`
When I try to destructure the item.sequence before execution, in order to check tildes occurrences for expansion, some values get partially moved, which leaves me forced to re-generate the sequence again and that may be overhead.
Any suggestions/better approaches in order to update the WordParts with tildes expanded? _another place of the code that may help with that, etc._

2024-12-11 08:30 UTC, HasanAlrimawi commented
> @dsherret I was able to solve the testcase you mentioned. However, in `src/shell/execute.rs fn execute_sequential_list` When I try to destructure the item.sequence before execution, in order to check tildes occurrences for expansion, some values get partially moved, which leaves me forced to re-generate the sequence again and that may be overhead. Any suggestions/better approaches in order to update the WordParts with tildes expanded? _(e.g. another place of the code that may help with that, etc.)_

@dsherret 
Any possible insights?

2025-04-09 18:11 UTC, dsherret commented
Sorry, I wasn't sure what the solution was here until I went to go work on it myself. Basically, we needed to parse the tildes and then expand them during execution. See #146

2025-04-09 21:18 UTC, closed without merging