Add basic `head` command
denoland/deno_task_shell pull request #93
Opened 2023-09-11 17:32 UTC by dahlia

This patch partially addresses issue #92.  It implements the very basic `head` command, with the following limitations:

- It can accept at most one file.
- The only options it supports are `-n`/`--lines`.
- The `-n`/`--lines` option cannot accept negative numbers.

2023-09-11 17:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/denoland/deno_task_shell?pullRequest=93) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/denoland/deno_task_shell?pullRequest=93) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/denoland/deno_task_shell?pullRequest=93) it.</sub>

2023-09-18 23:30 UTC, dsherret requested changes
Nice, thanks for this! I just have a few questions.

2023-09-18 23:30 UTC, dsherret commented on src/shell/commands/head.rs
> +        writer.write_all(&buf)?;
I think this needs to write only the size of the buffer and not the entire buffer which might contain data from a previous read at the end? We should extract out this function and add a unit test that triggers this scenario.

2023-09-18 23:30 UTC, dsherret commented on src/shell/commands/head.rs
> +      } else if let Some(line) = buf.split(|&b| b == b'\n').next() {
What happens to the rest of the lines in the buffer? I'm not sure how the tests work so I must be reading this wrong.

2023-09-21 09:32 UTC, dahlia commented
@dsherret  As you pointed out in your review, there were actually a bunch of bugs in copy_lines(), so I extracted it out to the module level and added unit tests for it to fix them.  Could you take another look at this?

2023-10-04 08:30 UTC, dahlia commented
Would there be anything left for me to fix?

2023-10-04 19:44 UTC, dsherret commented
@dahlia no, thanks! I just need to find the time to review the actual functionality. I'll get this in for Deno 1.38 which will be released in I think a month.

2023-10-04 21:00 UTC, dahlia commented
Thanks, I'm looking forward to it!

2023-10-27 16:48 UTC, dsherret approved these changes
LGTM. Thanks @dahlia!

2023-10-27 16:48 UTC, merged

2023-10-27 16:54 UTC, dahlia commented
Thank you!